In [ ]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score 

In [ ]:
dataset = load_digits()


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size=0.20, random_state=4)

In [ ]:
NN = MLPClassifier()


In [ ]:
NN.fit(x_train, y_train)


MLPClassifier()

In [ ]:
y_pred = NN.predict(x_test)


In [ ]:
accuracy = accuracy_score(y_test,y_pred)*100

confusion_mat = confusion_matrix(y_test,y_pred)


In [ ]:
print("Accuracy for Neural Network is:",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy for Neural Network is: 96.66666666666667
Confusion Matrix
[[38  0  0  0  0  0  0  0  0  0]
 [ 0 30  1  0  0  0  0  0  1  0]
 [ 0  0 41  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  0]
 [ 0  1  0  0 36  0  0  0  0  0]
 [ 0  0  0  0  0 37  0  0  0  1]
 [ 0  0  0  0  0  0 34  0  1  0]
 [ 0  0  0  0  0  0  0 38  0  0]
 [ 0  4  0  0  0  0  0  0 27  2]
 [ 0  0  0  0  0  0  0  0  0 35]]
